import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { templateFontVariables } from "./assets/fonts/fonts";
import "./styles/index.css";
import StoreProvider from "./store/StoreProvider";
import QueryClientProviderWrapper from "./shared/http/query-client.provider";
import MainNav from "./shared/components/main-nav/MainNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${templateFontVariables} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          <QueryClientProviderWrapper>
            <MainNav />
            {children}
          </QueryClientProviderWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
